---
title: "STA561 Final Project-Clustering"
author: "Eric Su"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mclust)
library(Rtsne)
```

```{r, warning = FALSE, message=FALSE}
library(readr)
music = read_csv("data/music_chrome_with_locations")
non_music = (ncol(music) - 3):ncol(music)
```

```{r, eval=FALSE}
n = 100
explain_var = rep(NA, n)
sil = rep(NA, n)
for (i in 1:n) {
  clust = kmeans(music[, -non_music], i, iter.max = 100)
  sil[i] = mean(silhouette(clust$cluster, dist(x = music[, -non_music])))
  explain_var[i] = clust$tot.withinss / clust$totss
}
par(mar=c(5, 4, 4, 6))
plot(1:n, explain_var, type = "b", main = "plot_title", xlab = "Number of Clusters", ylab = "Within groups sum of squares")
par(new = T)
plot(1:n, sil, type = "l", lty = 2, col = "red", axes = F, xlab = NA, ylab = NA)
axis(side = 4)
mtext("Average Silhouette width", side = 4, line = 3)
```

```{r, eval=FALSE}
library(factoextra)
library(cluster)
hclust_model = agnes(x = music[, -non_music], method = "ward")
fviz_dend(hclust_model, cex = 0.5, k = 10, lwd = 0.8, main = "hclust", horiz = T, ylab = "Height", show_labels = F)
fviz_dend(hclust_model, cex = 0.5, k = 10, lwd = 0.8, type = "circular", main = "hclust", ylab = "Height", show_labels = F)
fviz_dend(hclust_model, cex = 0.5, k = 10, lwd = 0.8, type = "phylogenic", main = "hclust", ylab = "Height", show_labels = F)

```


```{r, eval=FALSE}
n = 30
BIC = rep(NA, n)
sil = rep(NA, n)
for (i in 1:n) {
  model = Mclust(music[, -non_music], G = i, model = "EII")
  BIC[i] = model$bic
  sil[i] = mean(silhouette(model$classification, dist(x = music[, -non_music])))
}
par(mar=c(5, 4, 4, 6))
plot(1:n, BIC, type = "b", main = "plot_title", xlab = "Number of Clusters", ylab = "BIC")
par(new = T)
plot(1:n, sil, type = "l", lty = 2, col = "red", axes = F, xlab = NA, ylab = NA)
axis(side = 4)
mtext("Average Silhouette width", side = 4, line = 3)
```

```{r, eval=FALSE}
fpc::clusterboot(dist(music[, -non_music]), B = 1000, bootmethod = "boot", clustermethod = kmeansCBI, k = 5, count = F)
```

```{r, eval=FALSE}
cc = model$classification
index = cc %in% c(1, 2, 5, 16)
plot_data = data.frame(clust = cc[index], lon = music$lon[index], lat = music$lat[index])
ggplot(plot_data, aes(x = lon, y = lat, color = factor(clust)))+
  geom_jitter(width = 4, height = 4, alpha = 0.5)+
  theme_bw()
```

```{r, warning=FALSE, message=FALSE}
model = Mclust(music[, -non_music], G = 9, model = "EII", verbose = FALSE)
tsne <- Rtsne(music[, -non_music], dims = 2, perplexity=30, verbose=FALSE, max_iter = 500)
```

```{r}
ggplot()+
  geom_point(aes(x = tsne$Y[, 1], y = tsne$Y[, 2], color = music$continent), alpha = 0.5) +
  labs(x = "", y = "", title = "t-SNE plot colored by Continents")+
  coord_equal()+
  scale_color_hue(name = "Continent")+
  theme_bw()
```


```{r}
model = Mclust(music[, -non_music], G = 5, model = "EII", verbose = FALSE)
ggplot()+
  geom_point(aes(x = tsne$Y[, 1], y = tsne$Y[, 2], color = factor(model$classification)), alpha = 0.5) +
  labs(x = "", y = "", title = "t-SNE plot colored by Clusters")+
  coord_equal()+
  scale_color_hue(name = "Cluster")+
  theme_bw()
```

```{r}
model = Mclust(music[, -non_music], G = 9, model = "EII", verbose = FALSE)
ggplot()+
  geom_point(aes(x = tsne$Y[, 1], y = tsne$Y[, 2], color = factor(model$classification)), alpha = 0.5) +
  labs(x = "", y = "", title = "t-SNE plot colored by Clusters")+
  coord_equal()+
  scale_color_hue(name = "Cluster")+
  theme_bw()
```

```{r}
cc = model$classification
plot_data = data.frame(clust = cc, lon = music$lon, lat = music$lat)
ggplot(plot_data, aes(x = lon, y = lat, color = factor(clust)))+
  geom_jitter(width = 4, height = 4, alpha = 0.5)+
  theme_bw()
```

```{r}
music %>% 
  mutate(cluster = model$classification) %>%
  group_by(cluster) %>%
  summarise(Continent = names(which.max(table(continent))))
```

```{r}
music %>% 
  mutate(cluster = model$classification) %>%
  group_by(cluster) %>%
  summarise(`Country 1` = names(which.max(table(country))),
            `Country 2` = names(table(country) %>% sort(decreasing = T) %>% .[2]),
            `Country 3` = names(table(country) %>% sort(decreasing = T) %>% .[3]),
            `Country 4` = names(table(country) %>% sort(decreasing = T) %>% .[4]),
            `Country 5` = names(table(country) %>% sort(decreasing = T) %>% .[5]))
```

```{r}
music %>%
  mutate(cluster = model$classification) %>%
  group_by(country) %>%
  summarise(Purity = sort(table(cluster) / length(cluster), decreasing = T)[1])
```

```{r}
autoencoder_data = read_csv("autoencoder_data")

ggplot()+
  geom_point(aes(x = autoencoder_data$V1, y = autoencoder_data$V2, color = music$continent), alpha = 0.5) +
  labs(x = "", y = "", title = "Autoencoder plot colored by Continents")+
  coord_equal()+
  scale_color_hue(name = "Continent")+
  theme_bw()

ggplot()+
  geom_point(aes(x = autoencoder_data$V1, y = autoencoder_data$V2, 
                 color = factor(model$classification)), alpha = 0.5) +
  labs(x = "", y = "", title = "Autoencoder plot colored by Clusters")+
  coord_equal()+
  scale_color_hue(name = "Cluster")+
  theme_bw()
```

```{r}
model = Mclust(autoencoder_data[, 2:3], G = 9, model = "EII", verbose = FALSE)
ggplot()+
  geom_point(aes(x = autoencoder_data$V1, y = autoencoder_data$V2, 
                 color = factor(model$classification)), alpha = 0.5) +
  labs(x = "", y = "", title = "Autoencoder plot colored by Clusters")+
  coord_equal()+
  scale_color_hue(name = "Cluster")+
  theme_bw()
```
```{r}
music %>% 
  mutate(cluster = model$classification) %>%
  group_by(cluster) %>%
  summarise(Continent = names(which.max(table(continent))))
```

```{r}
music %>% 
  mutate(cluster = model$classification) %>%
  group_by(cluster) %>%
  summarise(`Country 1` = names(which.max(table(country))),
            `Country 2` = names(table(country) %>% sort(decreasing = T) %>% .[2]),
            `Country 3` = names(table(country) %>% sort(decreasing = T) %>% .[3]),
            `Country 4` = names(table(country) %>% sort(decreasing = T) %>% .[4]),
            `Country 5` = names(table(country) %>% sort(decreasing = T) %>% .[5]))
```

```{r}
model = Mclust(autoencoder_data[, 2:3], G = 5, model = "EII", verbose = FALSE)
purity = music %>%
  mutate(cluster = model$classification) %>%
  group_by(country) %>%
  summarise(Purity = sort(table(cluster) / length(cluster), decreasing = T)[1]) %>%
  arrange(desc(Purity))
colnames(purity)[1] = "Country"
knitr::kable(purity %>% head(5), digits = 2, caption = "Countries with Highest Purity")
```

